Uncaught TypeError occurs in some pages. #127
s-tip/stip-sns pull request #128
Opened 2020-12-01 04:50 UTC by tkhsknsk

stip-sns#127

2020-12-01 07:57 UTC, ta-hiroki approved these changes

2020-12-02 00:19 UTC, stmtstk requested changes
It seems that `hookBeforeSearch` does not need to return values (Ex. `return []`).
We should change a `return [];` to `return;`.
We also insert `return;` at the end of done block.

2020-12-02 00:26 UTC, tkhsknsk commented
Thank you for your review. Modify.

2020-12-02 01:29 UTC, stmtstk approved these changes

2020-12-02 01:29 UTC, merged