Fix "CSC community" to "All"
s-tip/stip-sns pull request #56
Opened 2020-07-22 05:50 UTC by ykoji8681

When I create a new post with "All" sharing range, the post will be displayed "CSC community" in SNS view.

I replaced the word in stip-sns.

Is it also necessary to replace in stip-rs files? @stmtstk 

```
src/ctirs/migrations/0008_auto_20190212_0215.py
src/ctirs/migrations/0036_auto_20191213_1145.py
```

2020-07-22 06:12 UTC, stmtstk requested changes
The migration files are automatically generated by modification of correspond `modles.py` files, so we must not edit these files directly.

In this case, we should modify this line.
https://github.com/s-tip/stip-rs/blob/master/src/ctirs/models/sns/feeds/models.py#L60

However, `const.SHARING_RANGE_CHOICES` is declared in stip-common, we should also pull request for stip-common.

https://github.com/s-tip/stip-common/blob/master/src/stip/common/const.py#L150

Thank you for your contribution.

---

migration file は models.py 変更時に  `python manage.py makemigrations` コマンドによって自動生成されるソースコードなので直接変更してはいけません。
ですので、 models. py の方を直します。該当 models.py は上記に記載した通りですが、choices の定義が stip-common 側にあるので、そちらを修正したうえで、stip-common にも PR すべきかと考えています。

2020-07-22 06:18 UTC, stmtstk commented
Sorry, you have already done a pull request of stip-common.

> Is it also necessary to replace in stip-rs files? @stmtstk
> src/ctirs/migrations/0008_auto_20190212_0215.py
> src/ctirs/migrations/0036_auto_20191213_1145.py

These files must not be modified. Please remove these files from changed files list.

2020-07-22 06:30 UTC, stmtstk commented
https://github.com/s-tip/stip-common/blob/master/src/stip/common/const.py

After you modified `const.py`, you must run...

```
cd /opt/s-tip/sns/bin
python manage.py makemigrations
```

You will see a new migration file under `src/ctirs/migrations`.
After that,

```
python manage.py migrate
```

Database migration will be executed.

Please include the new migration file into pull request.

2020-07-22 06:52 UTC, ykoji8681 commented
```
python manage.py makemigrations
```
causes the following error:
```
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
```
How do I set PYTHONPATH?

2020-07-22 06:56 UTC, stmtstk commented
You should add src in common and src in rs and src in SNS into `PYTHONPATH` .

For example, if you installed S-TIP through install.sh, you should set it below.

```
PYTHONPATH=/opt/s-tip/common/src:/opt/s-tip/rs/src:/opt/s-tip/sns/src
```

2020-07-22 07:45 UTC, ykoji8681 commented
Thanks, @stmtstk , I made a mistake. 

It works.

* I made a commit to cancel 2 migration files
* I opened another PR in stip-rs for adding a migration file.

    https://github.com/s-tip/stip-rs/pull/60

2020-07-27 00:17 UTC, stmtstk approved these changes

2020-07-27 00:18 UTC, merged