Fixed the process of replacing certain symbols. (for #89 issue)
s-tip/stip-sns pull request #92
Opened 2020-10-07 04:15 UTC by ta-hiroki

2020-10-07 04:34 UTC, tkhsknsk commented on src/feeds/static/js/feeds.js
> +        return file_name.replace(/[\. '"\(\)\:\/\?=\[\]\{\}\#\@\!\$\&\+\,\;]/g,'--');
Please adjust it to 2 indents.

2020-10-07 04:58 UTC, ta-hiroki commented on src/feeds/static/js/feeds.js
> +        return file_name.replace(/[\. '"\(\)\:\/\?=\[\]\{\}\#\@\!\$\&\+\,\;]/g,'--');
The correction was carried out.

2020-10-07 05:01 UTC, tkhsknsk approved these changes

2020-10-07 06:49 UTC, stmtstk requested changes
When an user posts with two files whose name is below...

```
test(1).txt
test{1}.txt
```

After posting, the user clicks `test{1}.txt` in CTI Element Dialog Box, `test(1).txt` is opened.

Please check the behavior.

2020-10-07 07:42 UTC, ta-hiroki commented
> https://github.com/s-tip/stip-sns/pull/92#pullrequestreview-503569897

@stmtstk 
I confirmed the content of the point.
Replace the "--" with the "--ASCII Code".

2020-10-07 23:59 UTC, stmtstk commented
Thank you. I confirmed it.
However, I am not sure that we should modify `confirm_indicators` in `search.js`.

@tkhsknsk , could you tell me whether we should modify it or not?

---

修正は確認できました。
しかし、search.js にも `confirm_indicators` があります。
search.js の中に feeds.js の一部を移植した修正を @tkhsknsk さんが行っていたと思うのですが、
`search.js` にも必要であるか教えてください。
必要であれば @ta-hiroki  さん、対応お願いします。

2020-10-08 00:29 UTC, ta-hiroki commented
@stmtstk 

Thank you for your confirmation.
"seach.js" has a similar occurrence.
I will fix it in the same way.

---

確認ありがとうございます。
seach.js にも同様の機能があります。
同じように修正を実施いたします。

2020-10-08 00:54 UTC, stmtstk approved these changes

2020-10-08 00:56 UTC, merged

2020-10-08 00:56 UTC, stmtstk commented
Thanks for your contribution.